version: '3'
services:
    btwnode:
        image: hasis/btwnode:09.04.2018
        volumes:
            - ./config/config.json:/usr/src/BTWChain/config.json
            - ./logs:/usr/src/BTWChain/src/logs
            - ./blockchain/blockchain.db:/usr/src/BTWChain/blockchain.db
        ports:
            - 8196:8196
        restart: always
